### PR TITLE
adds new example and some comments

### PR DESCRIPTION
**Pull request by Nowosad**

### CODE REVIEW

**Comment by kadyb** [comment]
Thanks! Here are my comments and responses to your analysis:

1. I see that you have chosen a variant of kmeans with data scaling, but in this case I believe that it would be better not to use it, so that the number of polygons in both analyses will be similar.
2. Ad 2, 3 and 8: My method is very limited, but the potential is greater. Specifically, I mean OBIA from commercial software where you can use classification rules and advanced postprocessing but I honestly don't know how to do it in R (see for example [eCognition](https://docs.ecognition.com/#eCognition_documentation/User%20Guide%20Developer/4%20Basic%20Rule%20Set%20Editing.htm) or [ArcGIS](https://desktop.arcgis.com/en/arcmap/latest/tools/spatial-analyst-toolbox/an-overview-of-the-generalization-tools.htm)).
3. Ad 5: I didn't do any testing here, but I read about some optimized methods. See [genieclust](https://cran.r-project.org/web/packages/genieclust/index.html) or [R*-Tree based algorithms](https://elki-project.github.io/benchmarking) (nevertheless, ELKI authors state here: "_But hierarchical clustering is not sensible for large data sets anyway_"). From [this benchmark](https://hdbscan.readthedocs.io/en/latest/performance_and_scalability.html#comparison-of-high-performance-implementations) I see that kmeans is the fastest method. Maybe it would be good idea to split the raster into smaller blocks to avoid running out of memory (on the one hand, block processing will be slower, but in this way we can reduce the maximum number of clusters from, e.g. 1000 to 500 and the prediction will be faster), and even better to parallelize it eventually.
4. Ad 6: I believe most of them can be addressed with the right parameters (sample size, number of clusters, input raster resolution) and postprocessing (raster smoothing level, etc.). Again, I think that methods from OBIA would be very useful here. Regarding the inclusion of NA, it probably comes from raster smoothing and perhaps this can maybe be changed in the `terra::focal()` parameters.

**Comment by kadyb** [comment]
Could you switch Quarto to RMarkdown? Then I would merge this PR. Quarto creates 18 unnecessary files....

**Comment by Nowosad** [comment]
Self-contain quarto html should be fine (see new push).

>I see that you have chosen a variant of kmeans with data scaling, but in this case I believe that it would be better not to use it, so that the number of polygons in both analyses will be similar.

I was unable to reproduce your non-scaled result. Could you share the code for this part?

>Ad 2, 3 and 8: My method is very limited, but the potential is greater. Specifically, I mean OBIA from commercial software where you can use classification rules and advanced postprocessing but I honestly don't know how to do it in R (see for example [eCognition](https://docs.ecognition.com/#eCognition_documentation/User%20Guide%20Developer/4%20Basic%20Rule%20Set%20Editing.htm) or [ArcGIS](https://desktop.arcgis.com/en/arcmap/latest/tools/spatial-analyst-toolbox/an-overview-of-the-generalization-tools.htm)).

Yes -- definitely having an R toolbox for segmentation would be great.

General: as you said, there are many parameters, methods, approaches, types of data, etc. to consider, try, and compare. If you want to start working in this direction -- I would suggest you start small and with clear objectives. Otherwise, it is easy to lose focus.

**Comment by kadyb** [comment]
> I was unable to reproduce your non-scaled result. Could you share the code for this part?

https://github.com/kadyb/image-segmentation/blob/main/ortho.R
Doesn't it work? I get very similar results to [this](https://user-images.githubusercontent.com/35004826/217364937-4e9e5c14-a71b-4601-9de5-8791b777d50b.png) from the issue in `supercells` repository.

**Comment by kadyb** [comment]
So in the end what conclusions can we take from this comparison? With these parameters, kmeans returns slightly worse results? Finally, `pixelcells` should be preferred as it is much faster for large data sets at this moment? (Maybe it would be nice including the silhouette index too?)

Just for reference, reducing the focal matrix from 7 to 5 (but more smaller polygons appear), I get:

```r
weighted.mean(rih1, as.numeric(vect_sf$area), na.rm = TRUE)
#> [1] 28.66399
weighted.mean(rih2, as.numeric(ortho_slic1$area), na.rm = TRUE)
#> [1] 31.14112
summary(rih1)
#>  Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
#> 2.00   21.78   29.01   31.00   37.66  145.58     233
summary(rih2)
#>  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#> 3.85   18.31   27.82   29.47   37.56   95.52 
```

**Comment by Nowosad** [comment]
1. If you reduce the focal window, you also create smaller polygons; thus for the comparison, you should also make the number of supercells larger (see the updated document). Then the results are more similar between the methods. 
2. The silhouette index: a) see the `reg_isolation` and `reg_distinction` functions in https://github.com/Nowosad/regional/; b) this index is not useful for superpixels (as they do not pretend to create segments, but their role is to oversegment the area); this measure is useful for the final results of segmentation/regionalization. 
3. Side note to the point above -- for larger data, you may start by creating supercells (as this approach is more efficient) and then use some clustering method, e.g., k-means or hclust, similarly to what you do with the pixels in your examples.
4. "So in the end what conclusions can we take from this comparison?". Some conclusions: a) your approach and the SLIC superpixel approach are very similar (read https://www.iro.umontreal.ca/~mignotte/IFT6150/Articles/SLIC_Superpixels.pdf) -- they both use k-means and take both spatial and non-spatial distances into consideration. The SLIC superpixel approach, however, uses local windows to make the calculations faster. Thus, the results of both approaches (given similar parameters) should also be fairly similar. b) At the same time, there will be some differences, especially regarding the distribution of the resulting polygons sizes: your approach creates polygons of various sizes, while the superpixel approach has two mechanisms (windows size and post-cleaning) to make the polygons' sizes more homogeneous. c) The supercells package expands the SLIC superpixels ideas (e.g., by allowing for other distance measures): this is not possible in your approach.

**Comment by kadyb** [comment]
> The time complexity for the classical k-means algorithm is O(N K I) where N
> is the number of data points (pixels in the image), K is the number of clusters (or
> seeds), and I is the number of iterations required for convergence. Our method
> achieves O(N) complexity (see Fig. 4), since we need to compute distances from
> any point to no more than eight cluster centers and the number of iterations is
> constant. Thus, SLIC is specific to the problem of superpixel segmentation, and
> unlike k-means, avoids several redundant distance calculations.

This is a pretty important quote.

Another point is that SLIC is a local method (takes into account pixels only from neighborhood), but kmeans in our case is global (samples are from the entire raster). Right?

> c) The supercells package expands the SLIC superpixels ideas (e.g., by allowing for other distance measures): this is not possible in your approach.

Technically we can implement another distance function in [predict kmeans](https://github.com/kadyb/image-segmentation/blob/c4ca98e11fed921bc8c72a22ac0cae4b90f2ceeb/landsat.R#L31) (pixel to cluster center), but this is rather stupid idea? Or another way for colud be input data transformation (e.g. log) or convert color space (HSV, LAB).

**Comment by kadyb** [comment]
We must also point out that the current way of segmentation using kmeans is very slow for large data ([landsat example](https://github.com/kadyb/image-segmentation/blob/main/landsat.R)). I think as solution we should process the raster in smaller blocks (e.g. 1000x1000) with reduced number of clusters (e.g. 1000) and then combine the results.

**Comment by Nowosad** [comment]
> Another point is that SLIC is a local method (takes into account pixels only from neighborhood), but kmeans in our case is global (samples are from the entire raster). Right?

Yep.

> Technically we can implement another distance function in [predict kmeans](https://github.com/kadyb/image-segmentation/blob/c4ca98e11fed921bc8c72a22ac0cae4b90f2ceeb/landsat.R#L31) (pixel to cluster center), but this is rather stupid idea? Or another way for colud be input data transformation (e.g. log) or convert color space (HSV, LAB).

Using other distances would make this approach much slower (plus, it is still a k-means approach, so you cannot use medians, etc. here). Data transformation is important for both approaches; however it depends on the context: converting to a LAB color space is recommended for segmentations of RGB images, but not for raster layers with proportions or raster time-series.

> We must also point out that the current way of segmentation using kmeans is very slow for large data ([landsat example](https://github.com/kadyb/image-segmentation/blob/main/landsat.R)). I think as solution we should process the raster in smaller blocks (e.g. 1000x1000) with reduced number of clusters (e.g. 1000) and then combine the results.

Yep, but preferably you would do it with some overlap and then find a way to resolve overlaps (I think I have seen a paper doing something like this). (Side note: you need to remember also that there is a bit of randomness in the k-means method).

**Comment by kadyb** [comment]
> Yep, but preferably you would do it with some overlap and then find a way to resolve overlaps (I think I have seen a paper doing something like this).

Or maybe modal filter would smooth out the transitions at the boundaries between blocks. There will be also an issue with cluster numbering. If the raster will be processed in blocks, the numbering will be independent (1:1000, 1:1000, 1:1000, etc.), so we will have to do a one more step to fix it.

**Comment by kadyb** [comment]
So we have done a much work over these three days. We already have the analysis and conclusions, so now we have to to write the paper ;)

**Comment by kadyb** [comment]
I implemented processing in blocks in [landsat_blocks.R](https://github.com/kadyb/image-segmentation/blob/main/landsat_blocks.R). It is ~3 times faster than the "all at once" example with more clusters. This can be further optimized, i.e. instead of returning small raster in each iteration, we can allocate vector of the length of the entire raster and replace the corresponding values.

Nevertheless, now the biggest problem is that the boundaries between blocks are very much visible.

**Comment by Nowosad** [comment]
I think the biggest problem is slightly different (but related) -- your approach does not control for uniform homogeneity of clusters across the blocks. 

For example, let's set k=5. One block may consist of five different values, and thus, the output would consist of perfectly homogeneous five clusters; another block, however, may consist of various values, but still will be forced to create five clusters -- in this case, each cluster will be very heterogeneous.

**Comment by kadyb** [comment]
Yeah, here we come to bigger problem of how to correctly define the number of clusters and whether to take into account lower scales / resolutions (I mean clustering in multiscales).

**Pull request merged**
